[project]
name = "mistral-ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "EngDawood", email = "davidhormos@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "markdowncleaner>=0.3.1",
    "mistralai>=1.10.0",
    "python-dotenv>=1.2.1",
]
